from sqlalchemy import Column, Integer, String
from app.database import Base

class FoodDB(Base):
    """
    Modèle SQLAlchemy = Table 'foods' dans Neon
    Représente les données nutritionnelles complètes d'un aliment
    """
    __tablename__ = "foods"
    
    id = Column(Integer, primary_key=True, index=True)
    alim_grp_code = Column(String, nullable=False, index=True)
    alim_ssgrp_code = Column(String, nullable=False, index=True)
    alim_ssssgrp_code = Column(String, nullable=False, index=True)
    alim_grp_nom_fr = Column(String, nullable=False)
    alim_ssgrp_nom_fr = Column(String, nullable=False)
    alim_ssssgrp_nom_fr = Column(String, nullable=False)
    alim_code = Column(String, nullable=False, unique=True, index=True)
    alim_nom_fr = Column(String, nullable=False, index=True)
    alim_nom_sci = Column(String, nullable=False)
    energie_reg_ue_kj = Column(String, nullable=True)
    energie_reg_ue_kcal = Column(String, nullable=True)
    energie_jones_avec_fibres_kj = Column(String, nullable=True)
    energie_jones_avec_fibres_kcal = Column(String, nullable=True)
    eau = Column(String, nullable=True)
    proteines_jones = Column(String, nullable=True)
    proteines = Column(String, nullable=True)
    glucides = Column(String, nullable=True)
    lipides = Column(String, nullable=True)
    sucres = Column(String, nullable=True)
    fructose = Column(String, nullable=True)
    galactose = Column(String, nullable=True)
    glucose = Column(String, nullable=True)
    lactose = Column(String, nullable=True)
    maltose = Column(String, nullable=True)
    saccharose = Column(String, nullable=True)
    amidon = Column(String, nullable=True)
    fibres = Column(String, nullable=True)
    polyols = Column(String, nullable=True)
    cendres = Column(String, nullable=True)
    alcool = Column(String, nullable=True)
    acides_organiques = Column(String, nullable=True)
    ags = Column(String, nullable=True)
    agmi = Column(String, nullable=True)
    agpi = Column(String, nullable=True)
    ag_butyrique = Column(String, nullable=True)
    ag_caproique = Column(String, nullable=True)
    ag_caprylique = Column(String, nullable=True)
    ag_caprique = Column(String, nullable=True)
    ag_laurique = Column(String, nullable=True)
    ag_myristique = Column(String, nullable=True)
    ag_palmitique = Column(String, nullable=True)
    ag_stearique = Column(String, nullable=True)
    ag_oleique = Column(String, nullable=True)
    ag_linoleique = Column(String, nullable=True)
    ag_alpha_linolenique = Column(String, nullable=True)
    ag_arachidonique = Column(String, nullable=True)
    EPA = Column(String, nullable=True)
    DHA = Column(String, nullable=True)
    cholesterol = Column(String, nullable=True)
    chlorure_de_sodium = Column(String, nullable=True)
    calcium = Column(String, nullable=True)
    chlorure = Column(String, nullable=True)
    cuivre = Column(String, nullable=True)
    fer = Column(String, nullable=True)
    iode = Column(String, nullable=True)
    magnesium = Column(String, nullable=True)
    manganese = Column(String, nullable=True)
    phosphore = Column(String, nullable=True)
    potassium = Column(String, nullable=True)
    selenium = Column(String, nullable=True)
    sodium = Column(String, nullable=True)
    zinc = Column(String, nullable=True)
    retinol = Column(String, nullable=True)
    beta_carotene = Column(String, nullable=True)
    vitamine_d = Column(String, nullable=True)
    vitamine_e = Column(String, nullable=True)
    vitamine_k1 = Column(String, nullable=True)
    vitamine_k2 = Column(String, nullable=True)
    vitamine_c = Column(String, nullable=True)
    vitamine_b1 = Column(String, nullable=True)
    vitamine_b2 = Column(String, nullable=True)
    vitamine_b3 = Column(String, nullable=True)
    vitamine_b5 = Column(String, nullable=True)
    vitamine_b6 = Column(String, nullable=True)
    vitamine_b9 = Column(String, nullable=True)
    vitamine_b12 = Column(String, nullable=True)